-- 종류 별로 가장 큰 물고기의 ID, 물고기 이름, 길이
-- ID 컬럼명은 ID, 이름 컬럼명은 FISH_NAME, 길이 컬럼명은 LENGTH
SELECT I.ID as ID, N.FISH_NAME as FISH_NAME, I.LENGTH as LENGTH
FROM FISH_INFO I, FISH_NAME_INFO N
WHERE I.FISH_TYPE = N.FISH_TYPE and (I.FISH_TYPE, I.LENGTH) IN (select FISH_TYPE, max(LENGTH) from FISH_INFO GROUP BY FISH_TYPE)